# Generated by Django 5.2 on 2025-04-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
