# Generated by Django 5.2 on 2025-04-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
